Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RestaurantFavoritizer.Models;
using RestaurantFavoritizer.DAL;

namespace RestaurantFavoritizer.Controllers
{
    public class RestaurantController : Controller
    {
        private FavContext db = new FavContext();

        // GET: Restaurant
        public ActionResult Index()
        {
            return View();
        }

        // GET: Restaurant/Details/5b v 
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RestaurantViewClass RestaurantView;
            FavUser user;

            user = FavUserMaster.GetCurrentUser(db);
            //Restaurant restaurant = db.Restaurants.Find(id);
            Restaurant restaurant = RestaurantMaster.GetRestaurantByID(id,db);

            if (restaurant == null)
            {
                return HttpNotFound();
            }

            try
            {
                RestaurantView = new RestaurantViewClass { Restaurant = restaurant, FavUser = user };
                return View(RestaurantView);
            }
            catch
            {
                return HttpNotFound();
            }
        }

        public ActionResult Place(string placeID, string name, string phone, string address, float lat, float lng, string url, string site)
        {
            if (placeID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Restaurant restaurant = db.Restaurants.FirstOrDefault(Restaurant => Restaurant.MainLocation.GooglePlaceID == placeID);
            if (restaurant == null)
            {
                FavUser user;
                Location location;
                //Favorite fav;
                Perk perk;
                string website;
                perk = new Perk { };
                //fav = new Favorite { };
                user = FavUserMaster.GetCurrentUser(db);
                location = new Location { GooglePlaceID = placeID };

                if(site != null && site.Trim() != String.Empty)
                {
                    if (!site.StartsWith("http"))
                    {
                        website = "https://" + site;
                    }
                    else
                    {
                        website = site;
                    }
                }
                else
                {
                    website = string.Empty;
                }


                location.Latitude = lat;
                location.Longitude = lng;
                location.AddressLn1 = address;
                location.PhoneNo = phone;
                location.GooglePlaceID = placeID;
                location.ContentString = "Be the first to add a description and earn fav points!";
                location.Annotation = url;
                location.City = user.Location.City;
                restaurant = new Restaurant { RestaurantName = name };
                restaurant.MainLocation = location;
                restaurant.IconName = "restaurant";

                //fav.CreateDate = DateTime.Now;
                //fav.FavUserID = user.FavUserID;
                //fav.RestaurantID = restaurant.RestaurantID;
                restaurant.MainLocation = location;
                restaurant.WebSiteURL = website;
                restaurant.CreateDate = DateTime.Now;
                perk.CreateDate = DateTime.Now;
                perk.PerkType = PerkType.AddedRestaurant;
                perk.FavUserID = user.FavUserID;
                perk.Value = 2;

                db.FavUsers.Attach(user);
                user.PerkTotal = user.PerkTotal + perk.Value;

                db.Locations.Add(location);
                db.Restaurants.Add(restaurant);
                //db.Favorites.Add(fav);
                db.Perks.Add(perk);

                try
                {
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    e.ToString();
                }

            }
            return RedirectToAction("Details", new { id = restaurant.RestaurantID });
        }

        [HttpPost]
        public ActionResult ShowMenu(Restaurant rest)
        {
            if (ModelState.IsValid)
            {
                RestaurantViewClass RestaurantView;

                //Restaurant restaurant = db.Restaurants.Find(rest.RestaurantID);
                Restaurant restaurant = RestaurantMaster.GetRestaurantByID(rest.RestaurantID,db);

                FavUser user;

                user = FavUserMaster.GetCurrentUser(db);

                if (restaurant == null)
                {
                    return HttpNotFound();
                }

                try
                {
                    RestaurantView = new RestaurantViewClass { Restaurant = restaurant, FavUser = user };

                    return PartialView(RestaurantView);
                }
                catch
                {
                    return HttpNotFound();
                }
            }
            return null;
        }

        [HttpPost]
        public ActionResult AddNewFood(Restaurant rest, FoodItem food)
        {
            if (ModelState.IsValid)
            {
                food.RestaurantID = rest.RestaurantID;
                food.CreateDate = DateTime.Now;
                db.FoodItems.Add(food);
                db.SaveChanges();

                return PartialView(food);
            }
            return null;
        }

        [HttpPost]
        public ActionResult AddNewDrink(Restaurant rest, DrinkItem drink)
        {
            if (ModelState.IsValid)
            {
                drink.RestaurantID = rest.RestaurantID;
                drink.CreateDate = DateTime.Now;
                db.DrinkItems.Add(drink);
                db.SaveChanges();

                return PartialView(drink);
            }
            return null;
        }

        [HttpPost]
        public ActionResult AddNewEmployee(Restaurant rest, Employee employee)
        {
            if (ModelState.IsValid)
            {
                employee.RestaurantID = rest.RestaurantID;
                employee.CreateDate = DateTime.Now;
                db.Employee.Add(employee);
                db.SaveChanges();

                return PartialView(employee);
            }
            return null;
        }

       

        [HttpPost]
        public bool EditRestaurant(Restaurant rest, Location loc)
        {
            if (ModelState.IsValid)
            {
                if (rest.WebSiteURL != null && rest.WebSiteURL.Trim() != String.Empty)
                {
                    if (!rest.WebSiteURL.ToLower().StartsWith("http"))
                    {
                        rest.WebSiteURL = "http://" + rest.WebSiteURL;
                    }
                }

                db.Restaurants.Attach(rest);
                var entry = db.Entry(rest);
                entry.Property(e => e.RestaurantName).IsModified = true;
                entry.Property(e => e.WebSiteURL).IsModified = true;
                entry.Property(e => e.RestaurantType).IsModified = true;

                db.Locations.Attach(loc);
                var entry2 = db.Entry(loc);
                entry2.Property(f => f.AddressLn1).IsModified = true;
                entry2.Property(f => f.PhoneNo).IsModified = true;
                entry2.Property(f => f.City).IsModified = true;
                entry2.Property(f => f.State).IsModified = true;
                entry2.Property(f => f.ZipCode).IsModified = true;

                try
                {
                    db.SaveChanges();
                    return true;
                }
                catch
                {
                    return false;
                }
            }

                return false;
        }

        [HttpPost]
        public bool ToggleFoodLike(FoodContribution foodContributionUpdate)
        {
            if (ModelState.IsValid)
            {
                FavUser user;

                user = FavUserMaster.GetCurrentUser(db);

                FoodContribution food = db.FoodContributions.FirstOrDefault(a => a.FoodItemID == foodContributionUpdate.FoodItemID && a.FavUserID == user.FavUserID);

                if (food != null)
                {
                    food.LikeStatus = foodContributionUpdate.LikeStatus;
                        
                    db.FoodContributions.Attach(food);
                    var entry = db.Entry(food);
                    entry.Property(e => e.LikeStatus).IsModified = true;
                } else
                {
                    foodContributionUpdate.FavUserID = user.FavUserID;

                    db.FoodContributions.Add(foodContributionUpdate);
                }

                try
                {
                    db.SaveChanges();
                    return true;
                }
                catch
                {
                    return false;
                }
            }

            return false;
        }

        [HttpPost]
        public bool ToggleDrinkLike(DrinkContribution drinkContributionUpdate)
        {
            if (ModelState.IsValid)
            {
                FavUser user;

                user = FavUserMaster.GetCurrentUser(db);

                DrinkContribution drink = db.DrinkContributions.FirstOrDefault(a => a.DrinkItemID == drinkContributionUpdate.DrinkItemID && a.FavUserID == user.FavUserID);

                if (drink != null)
                {
                    drink.LikeStatus = drinkContributionUpdate.LikeStatus;

                    db.DrinkContributions.Attach(drink);
                    var entry = db.Entry(drink);
                    entry.Property(e => e.LikeStatus).IsModified = true;
                }

Views/Shared/AddNewRestaurant.cshtml
@model RestaurantFavoritizer.Models.Restaurant

<div class="feed-post-container">
    <div class="feed-post">
        @*<a class="restaurant-favorite-add pull-right" href="#" title="Add To Favorites" data-json="{&quot;RestaurantID&quot;: @Model.RestaurantID,&quot;RestaurantName&quot;: &quot;@Model.RestaurantName&quot;}">
            <i class="fa fa-star"></i>
        </a>*@
        <span>@Html.ActionLink(Model.RestaurantName, "Details", "Restaurant", new { id = Model.RestaurantID }, null)</span>
        <span class="feed-type">@Model.RestaurantType</span>
        <span class="feed-location">@Model.MainLocation.AddressLn1 @Model.MainLocation.City, @Model.MainLocation.State</span>
        <span class="feed-date text-muted">@Model.CreateDate</span>
    </div>
</div>

Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Info";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

Views/Shared/RestaurantModal.cshtml
@model RestaurantFavoritizer.Models.MainViewClass
<script type="text/javascript" src="@Url.Content("/Scripts/mapModal.js")"></script>
<script type="text/javascript" src="@Url.Content("/Scripts/jquery.validate.min.js")"></script>

<div id="restaurantModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add Restaurant (Click on the map to add the location)</h4>
            </div>
            <div class="modal-body">
                <div id="map" class="modal-map"></div>
                <input id="pac-input" class="map-search" type="text" placeholder="Search Box">
                <div class="required-text"><span class="text-danger">*</span> Indicates required field</div>
                <form id="restaurantEventForm" action="/Home/AddNewRestaurant" method="post">
                    <div class="form-group form-inline">
                        <label for="RestaurantName">Restaurant Name <span class="text-danger">*</span></label>
                        <div class="form-inline">
                            @Html.TextBox("RestaurantName", null, new { @class = "form-control", @maxlength = "100", @required = "" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="WebSiteUrl">Website</label>
                        @Html.TextBox("WebSiteUrl", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="PhoneNo">Phone Number</label>
                        @Html.TextBox("PhoneNo", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Food Type</label>
                        @Html.EnumDropDownListFor(model => model.RestaurantType, null, new { @class = "form-control" })
                    </div>
                    @Html.Hidden("Latitude")
                    @Html.Hidden("Longitude")
                    <input class="btn btn-default submit" type="submit" value="Save New Restaurant" id="Save" />
                    <div id="msg" class="msg"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" onmouseup="ClearValues();" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/jscript">
    $('#restaurantEventForm').submit(function (e) {
        e.preventDefault();
    }).validate({
            rules: {
                RestaurantName: "required",
                RestaurantType: "required"
            },
            messages: {
                RestaurantName: "Please enter a restaurant name"
            },
            submitHandler: function (form) {
                var url = $(form).attr("action");
                var formData = $(form).serialize();
                $.ajax({
                    url: url,
                    data: formData,
                    success: function (data) {
                        if (data) {
                            $('#feed').prepend(data);
                            $('#msg').html('<div class="alert alert-dismissible alert-success"><button type="button" class="close" data-dismiss="alert">×</button>\
                        <span>New Restaurant Added. Thank you for helping to improve Favoritizer.</span></div>');
                        } else {
                            $('#msg').html('<div class="alert alert-dismissible alert-danger"><button type="button" class="close" data-dismiss="alert">×</button>\
                                <span>Failed to add restaurant! Make sure all forms are filled out and you selected a location on the map.</span></div>');
                        }
                    },
                    type: 'POST'
                });
            }
        });

    function ClearValues() {
        $("#RestaurantName").val("");
        //$("#Latitude").val("");
        //$("#Longitude").val("");
        $("#WebSiteUrl").val("");
        $("#PhoneNo").val("");
        $('#msg').html('');
    }
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Restautant Favoritizer</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Restaurant Favoritizer", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/"><i class="fa fa-home"></i>&nbsp; Home</a></li>
                    <li><a href="/MyFavorites"><i class="fa fa-star"></i>&nbsp; Favorites</a></li>
                    <li><a href="/Map"><i class="fa fa-map"></i>&nbsp; Map</a></li>
                    <li><a href="/Profile"><i class="fa fa-user"></i>&nbsp; Profile</a></li>
                </ul>
                <form id="SearchNav" class="navbar-form navbar-left" action="/Home/Search" method="post" role="search">
                    <div class="form-group">
                        <div class="input-group">
                            @Html.TextBox("SearchString", null, new { @class = "form-control", @placeholder = "Search" })
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit" id="SearchNav"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </div>
                </form>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="fav-footer">
            <p>&copy; @DateTime.Now.Year - Restaurant Favoritizer</p>
        </footer>
    </div>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDFRB5faj9FozFL-YUA513d_WaeVyLxDSg&libraries=places&callback=initMap" async defer></script>
    @RenderSection("scripts", required: false)
</body>
</html>